config/routes.rb
Rails.application.routes.draw do
  resources :borrows

  get 'library/index'

  get 'isis/index'

  get 'icon/index'

  resources :roles

  resources :books

  resources :teachings

  resources :departments

  resources :colleges

  resources :courses

  get 'welcome/index'

  devise_for :users
  scope "/admin" do
    resources :users
  end
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.admin?
      can :manage, :all
    elsif user.instructor?
      can :read, :all
      can :create, :all
      can :update, :all
      can :manage, Teaching
    elsif user.student?
      can [:create, :read, :destroy], Teaching
      can :read, :all
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :borrows
  has_many :users, :through => :borrows

	def self.search(search)
		where("title like ?", "%#{search}%") 
	end
end

app/models/borrow.rb
class Borrow < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

end

app/models/college.rb
class College < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :teachings
  has_many :users, :through => :teachings

	def self.search(search)
		where("name like ?", "%#{search}%") 
	end
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/teaching.rb
class Teaching < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role

  before_save :assign_role

  has_many :teachings
  has_many :courses, :through => :teachings

  has_many :borrows
  has_many :books, :through => :borrows

	def assign_role
	  self.role = Role.find_by name: "Student" if self.role.nil?
	end

	def admin?
  	self.role.name == "Admin"
	end

	def instructor?
  	self.role.name == "Instructor"
	end

	def student?
  	self.role.name == "Student"
	end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  # before_action :set_college, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:name)
    end
end

app/controllers/icon_controller.rb
class IconController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
	
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/icon_helper.rb
module IconHelper
end

app/helpers/isis_helper.rb
module IsisHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/teachings_helper.rb
module TeachingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/colleges/_form.html.erb
<%= form_for(@college) do |f| %>
  <% if @college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% @college.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<h1>Editing College</h1>

<%= render 'form' %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/index.html.erb
<h1>All Colleges</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= link_to 'Show', college %></td>
        <td>
          <% if can? :update, college %> 
          <%= link_to 'Edit', edit_college_path(college) %>
          <% end %> 
        </td>
        <td>
          <% if can? :destroy, college %> 
          <%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, College %> 
  <%= link_to 'New College', new_college_path %>
<% end %>

<%= link_to 'Back', isis_index_path %> 

app/views/colleges/new.html.erb
<h1>New College</h1>

<%= render 'form' %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>