config/routes.rb
Rails.application.routes.draw do
  resources :borrows

  get 'library/index'

  get 'isis/index'

  get 'icon/index'

  resources :roles

  resources :books

  resources :teachings

  resources :departments

  resources :colleges

  resources :courses

  get 'welcome/index'

  devise_for :users
  scope "/admin" do
    resources :users
  end
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.admin?
      can :manage, :all
    elsif user.instructor?
      can :read, :all
      can :create, :all
      can :update, :all
      can :manage, Teaching
    elsif user.student?
      can [:create, :read, :destroy], Teaching
      can :read, :all
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :borrows
  has_many :users, :through => :borrows

	def self.search(search)
		where("title like ?", "%#{search}%") 
	end
end

app/models/borrow.rb
class Borrow < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

end

app/models/college.rb
class College < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :teachings
  has_many :users, :through => :teachings

	def self.search(search)
		where("name like ?", "%#{search}%") 
	end
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/teaching.rb
class Teaching < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role

  before_save :assign_role

  has_many :teachings
  has_many :courses, :through => :teachings

  has_many :borrows
  has_many :books, :through => :borrows

	def assign_role
	  self.role = Role.find_by name: "Student" if self.role.nil?
	end

	def admin?
  	self.role.name == "Admin"
	end

	def instructor?
  	self.role.name == "Instructor"
	end

	def student?
  	self.role.name == "Student"
	end
end

app/controllers/icon_controller.rb
class IconController < ApplicationController
  def index
  end
end

app/controllers/teachings_controller.rb
class TeachingsController < ApplicationController
  # before_action :set_teaching, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /teachings
  # GET /teachings.json
  def index
    @teachings = Teaching.where('user_id = ?', current_user.id)
  end

  # GET /teachings/1
  # GET /teachings/1.json
  def show
  end

  # GET /teachings/new
  def new
    @teaching = Teaching.new
  end

  # GET /teachings/1/edit
  def edit
  end

  # POST /teachings
  # POST /teachings.json
  def create
    @teaching = Teaching.new(teaching_params)
    @teaching.user_id = current_user.id 

    respond_to do |format|
      if @teaching.save
        format.html { redirect_to @teaching, notice: 'Successfully enrolled in class.' }
        format.json { render :show, status: :created, location: @teaching }
      else
        format.html { render :new }
        format.json { render json: @teaching.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachings/1
  # PATCH/PUT /teachings/1.json
  def update
    respond_to do |format|
      if @teaching.update(teaching_params)
        format.html { redirect_to @teaching, notice: 'Class was successfully updated.' }
        format.json { render :show, status: :ok, location: @teaching }
      else
        format.html { render :edit }
        format.json { render json: @teaching.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachings/1
  # DELETE /teachings/1.json
  def destroy
    @teaching.destroy
    respond_to do |format|
      format.html { redirect_to teachings_url, notice: 'Successfully dropped class.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teaching
      @teaching = Teaching.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teaching_params
      params.require(:teaching).permit(:term, :course_id,  :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
	
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/icon_helper.rb
module IconHelper
end

app/helpers/isis_helper.rb
module IsisHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/teachings_helper.rb
module TeachingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/teachings/_form.html.erb
<%= form_for(@teaching) do |f| %>
  <% if @teaching.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teaching.errors.count, "error") %> prohibited this teaching from being saved:</h2>

      <ul>
      <% @teaching.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term %><br>
    <%= f.text_field :term %>
  </div>
  <div class="actions">
    <%= submit_tag 'Update Class' %> 
  </div>
<% end %>

app/views/teachings/edit.html.erb
<h1>Editing Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @teaching %> |
<%= link_to 'Back', teachings_path %>

app/views/teachings/index.html.erb
<h1>My Classes</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Term</th>
      <th>Course</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachings.each do |teaching| %>
      <tr>
        <td><%= teaching.term %></td>
        <td><%= link_to Course.find(teaching.course_id).name, teaching %></td>
        <td>
          <% if can? :update, teaching %> 
          <%= link_to 'Edit', edit_teaching_path(teaching) %>
          <% end %> 
        </td>
        <td>
          <% if can? :destroy, teaching %> 
          <%= link_to 'Drop', teaching, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', icon_index_path %> 

app/views/teachings/new.html.erb
<h1>New Teaching</h1>

<%= render 'form' %>

<%= link_to 'Back', teachings_path %>

app/views/teachings/show.html.erb
<p>
  <strong>Term:</strong>
  <%= @teaching.term %>
</p>
<p>
  <strong>Course:</strong>
  <%= (@course = Course.find(@teaching.course_id)).name %> 
</p>
<p>
  <strong>DropBox:</strong>
  <%= @course.dropbox %> 
</p>
<p>
  <strong>News:</strong>
  <%= @course.news %> 
</p>
<p>
  <strong>Quiz:</strong>
  <%= @course.quiz %> 
</p>
<p>
  <strong>Content:</strong>
  <%= @course.content %> 
</p>
<% if can? :update, Teaching %> 
  <%= link_to 'Edit', edit_teaching_path(@teaching) %> |
<% end %> 
<%= link_to 'Back', teachings_path %>