config/routes.rb
Rails.application.routes.draw do
  resources :borrows

  get 'library/index'

  get 'isis/index'

  get 'icon/index'

  resources :roles

  resources :books

  resources :teachings

  resources :departments

  resources :colleges

  resources :courses

  get 'welcome/index'

  devise_for :users
  scope "/admin" do
    resources :users
  end
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.admin?
      can :manage, :all
    elsif user.instructor?
      can :read, :all
      can :create, :all
      can :update, :all
      can :manage, Teaching
    elsif user.student?
      can [:create, :read, :destroy], Teaching
      can :read, :all
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :borrows
  has_many :users, :through => :borrows

	def self.search(search)
		where("title like ?", "%#{search}%") 
	end
end

app/models/borrow.rb
class Borrow < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

end

app/models/college.rb
class College < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :teachings
  has_many :users, :through => :teachings

	def self.search(search)
		where("name like ?", "%#{search}%") 
	end
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/teaching.rb
class Teaching < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role

  before_save :assign_role

  has_many :teachings
  has_many :courses, :through => :teachings

  has_many :borrows
  has_many :books, :through => :borrows

	def assign_role
	  self.role = Role.find_by name: "Student" if self.role.nil?
	end

	def admin?
  	self.role.name == "Admin"
	end

	def instructor?
  	self.role.name == "Instructor"
	end

	def student?
  	self.role.name == "Student"
	end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :set_borrow, only: [:show, :edit, :update, :destroy]

  # GET /borrows
  # GET /borrows.json
  def index
    @borrows = Borrow.all
  end

  # GET /borrows/1
  # GET /borrows/1.json
  def show
  end

  # GET /borrows/new
  def new
    @borrow = Borrow.new
  end

  # GET /borrows/1/edit
  def edit
  end

  # POST /borrows
  # POST /borrows.json
  def create
    @borrow = Borrow.new(borrow_params)
    @borrow.due = 14.days.from_now

    respond_to do |format|
      if @borrow.save
        format.html { redirect_to borrows_path, notice: 'Book was successfully borrowed.' }
        format.json { render :show, status: :created, location: @borrow }
      else
        format.html { render :new }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /borrows/1
  # PATCH/PUT /borrows/1.json
  def update
    respond_to do |format|
      if @borrow.update(borrow_params)
        format.html { redirect_to borrows_path, notice: 'Book was successfully renewed.' }
        format.json { render :index, status: :ok }
      else
        format.html { render :index }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrows/1
  # DELETE /borrows/1.json
  def destroy
    @borrow.destroy
    respond_to do |format|
      format.html { redirect_to borrows_url, notice: 'Book successfully returned.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrow
      @borrow = Borrow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrow_params
      params.require(:borrow).permit(:book_id, :user_id, :due)
    end
end

app/controllers/icon_controller.rb
class IconController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
	
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/icon_helper.rb
module IconHelper
end

app/helpers/isis_helper.rb
module IsisHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/teachings_helper.rb
module TeachingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/borrows/_form.html.erb
<%= form_for(@borrow) do |f| %>
  <% if @borrow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@borrow.errors.count, "error") %> prohibited this borrow from being saved:</h2>

      <ul>
      <% @borrow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/borrows/edit.html.erb
<h1>Editing Borrow</h1>

<%= render 'form' %>

<%= link_to 'Show', @borrow %> |
<%= link_to 'Back', borrows_path %>

app/views/borrows/index.html.erb
<h1>My Books</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Book Title</th>
      <th>Book Author</th>
      <th>Due Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @borrows.each do |borrow| %>
      <tr>
        <td><%= link_to Book.find(borrow.book_id).title, book_path(borrow.book_id) %></td>
        <td><%= Book.find(borrow.book_id).author %></td>
        <td><%= borrow.due %></td>
        <td><%= link_to 'Renew', borrow_path({:id => borrow.id, :borrow => {:due => borrow.due + 14.days}}), method: :patch %></td>
        <td><%= link_to 'Return', borrow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', library_index_path %>

app/views/borrows/new.html.erb
<h1>New Borrow</h1>

<%= render 'form' %>

<%= link_to 'Back', borrows_path %>

app/views/borrows/show.html.erb
<%= link_to 'Edit', edit_borrow_path(@borrow) %> |
<%= link_to 'Back', borrows_path %>