config/routes.rb
Rails.application.routes.draw do
  resources :borrows

  get 'library/index'

  get 'isis/index'

  get 'icon/index'

  resources :roles

  resources :books

  resources :teachings

  resources :departments

  resources :colleges

  resources :courses

  get 'welcome/index'

  devise_for :users
  scope "/admin" do
    resources :users
  end
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.admin?
      can :manage, :all
    elsif user.instructor?
      can :read, :all
      can :create, :all
      can :update, :all
      can :manage, Teaching
    elsif user.student?
      can [:create, :read, :destroy], Teaching
      can :read, :all
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :borrows
  has_many :users, :through => :borrows

	def self.search(search)
		where("title like ?", "%#{search}%") 
	end
end

app/models/borrow.rb
class Borrow < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

end

app/models/college.rb
class College < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :teachings
  has_many :users, :through => :teachings

	def self.search(search)
		where("name like ?", "%#{search}%") 
	end
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/teaching.rb
class Teaching < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role

  before_save :assign_role

  has_many :teachings
  has_many :courses, :through => :teachings

  has_many :borrows
  has_many :books, :through => :borrows

	def assign_role
	  self.role = Role.find_by name: "Student" if self.role.nil?
	end

	def admin?
  	self.role.name == "Admin"
	end

	def instructor?
  	self.role.name == "Instructor"
	end

	def student?
  	self.role.name == "Student"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
	
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/icon_helper.rb
module IconHelper
end

app/helpers/isis_helper.rb
module IsisHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/teachings_helper.rb
module TeachingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<div class="navbar-wrapper">
  <div class="container">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button class="active">
          <%= link_to "Kwahsr", root_path, :class => "navbar-brand"%> 
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">ISIS <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "ISIS Home", isis_index_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Courses", courses_path %></li>
                  <li><%= link_to "Departments", departments_path %></li>
                  <li><%= link_to "Colleges", colleges_path %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">ICON <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "ICON Home", icon_index_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "My Classes", teachings_path %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Library <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Library Home", library_index_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "All Books", books_path %></li>
                  <li><%= link_to "My Books", borrows_path %></li>
                </ul>
              </li>
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
            <% end %>
            </li>
          </ul>
          <% if !user_signed_in? %>
          <div class="navbar-form navbar-right">
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="form-group">
              <%= f.text_field :email, autofocus: true, :class => 'form-control', :placeholder => 'Email' %>
             </div>
            <div class="form-group">
              <%= f.password_field :password, autocomplete: "off", :class => 'form-control', :placeholder => 'Password' %>
            </div>
            <%= f.submit "Log in", :class => 'btn btn-warning' %>
          <% end %>
          </div>
          <% else %>
          <div class="navbar-form navbar-right">
          <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-warning'  %>
        </div>
          <% end %>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kwahsr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</div>
</body>
</html>